### ISSUE TITLE
I would love to join Recyclero

### ISSUE THREAD

**Issue by iabdr** [Recyclero/Recyclero#10]
### Bio
I’m Abd, a Student, Developer, Learner and Graphic Designer.
I’m interested in Web & App Development.
I’m currently learning Flutter, React Native & Python.

### Reason
I want to contribute and help the community .

**GitHub:** https://github.com/abd-ar 

[github_handle]: https://github.com/username

**Comment by 0x48piraj** [comment]
Sorry for not being active. Sent the invite. Please make sure to publicize your membership.
