### ISSUE TITLE
I would love to join Recyclero

### ISSUE THREAD

**Issue by thuongtruong1009** [Recyclero/Recyclero#15]
### Bio

My name is Tran Nguyen Thuong Truong - thuongtruong1009.
I come from VietNam with open-source code love.
My Github link: https://github.com/thuongtruong1009
My Github ID: thuongtruong1009
Nice to meet you!
Thank you!

### Reason

**GitHub:** [@thuongtruong1009][github_handle] 

[github_handle]: https://github.com/thuongtruong1009

**Comment by 0x48piraj** [comment]
Sent the invite. Please make sure to publicize your membership.

**Comment by thuongtruong1009** [comment]
Thank you very much!
