### ISSUE TITLE
I would love to join Recyclero

### ISSUE THREAD

**Issue by aritra1804** [Recyclero/Recyclero#18]
### Bio

Let me introduce myself 🙂 I am Aritra, as you all coding is my hobby and life style. I met coding at the very beginning of my academic career. And now I have about 5 years of Web development and AI/ML devlopment experience. I am currently working at CSIR Labs as an Cloud Developer Intern. Besides I am a undergraduate at SRMIST.

### Reason

One of the reasons I want to join Recyclero is to contribute to the environmental projects it does. Also I would like to learn and connect with members from different fields and work with them to help the environment.

**GitHub:** [aritra1804][github_handle] 

[github_handle]: https://github.com/aritra1804

**Comment by 0x48piraj** [comment]
That's awesome. Sent the invite and sorry for the late reply. Please make sure to publicize your membership.
