### ISSUE TITLE
I would love to join Recyclero

### ISSUE THREAD

**Issue by sharmas1ddharth** [Recyclero/Recyclero#20]
### Bio

My name is Siddharth Sharma. I am a Machine Learning Engineer based in Bengaluru, India

### Reason

I want to contribute to the process of recycling waste using deep learning

**GitHub:** [@sharmas1ddharth][github_handle] [](https://github.com/sharmas1ddharth)

[github_handle]: https://github.com/sharmas1ddharth

**Comment by 0x48piraj** [comment]
Sent the invite. Please make sure to publicize your membership.
