### ISSUE TITLE
I would love to join Recyclero

### ISSUE THREAD

**Issue by ps-19** [Recyclero/Recyclero#6]
### Bio 
I am a college student. Open-Source enthusiatic, have strong coding background and a certified web developer.

### Reason

As an open source contributor i need a community to mentor me. Help me or get helped.

**GitHub:** [@username][github_handle] 

[github_handle]: https://github.com/ps-19/

**Comment by 0x48piraj** [comment]
Sent the invite. Please make sure to publicize your membership.
